# Each sheet name maps to a list of fields IN ORDER
# These must match the column order in your Excel sheet
SHEET_CONFIG = {
    "L2": [
        "amounts_transferred",
        "income_from_investments",
        "other_income",
        "total_income",
        "total_expense",
        "profit_before_tax",
        "profit_after_tax",
        "opening_balance",
        "net_profit_till_date"
    ],
    "L3": [
        "shareholders_funds",
        "borrowings",
        "policyholders_funds"
    ],
    "L4": [
        "first_year_premiums",
        "renewal_premiums",
        "single_premiums",
        "premium_income_india",
        "premium_income_outside_india",
        "net_total"
    ],
    "L5": [
        "first_year_commission",
        "ry_premium_commission",
        "single_premium_commission",
        "direct_commission",
        "reinsurance_accepted",
        "reinsurance_ceded",
        "rewards",
        "channelwise breakup",
        "agents",
        "banca",
        "ca_others",
        "broker",
        "micro_agents",
        "direct_online",
        "direct_others",
        "csc",
        "web_aggregator",
        "imf",
        "pos_direct",
        "others",
        "business_india",
        "business_outside_india",
        "total_commission_and_rewards"
    ],
    "L6": [
        "employee_remuneration",
        "travel",
        "training",
        "rent",
        "repairs",
        "print_stationery",
        "comms",
        "legal_professional",
        "medical_fee",
        "auditor",
        "advertisement",
        "interest_bank_charges",
        "depreciation",
        "brand_trade",
        "bd_sales_promotion",
        "stamp_duty",
        "it",
        "gst",
        "others",
        "inside_india",
        "outside_india",
        "total_operating_expenses"
    ],
    "L7": [
        "claims_by_death",
        "claims_by_maturity",
        "annuity_pension",
        "survival_benefit",
        "periodical_benefit",
        "health",
        "surrender",
        "withdrawals",
        "discontinuance_payments",
        "bonus",
        "interest_on_unclaimed",
        "other_benefits",
        "benefits_paid_gross",
        "reinsurance_ceded",
        "reinsurance_accepted",
        "benefits_paid_net"
    ],
    "L9": [
        "promoters_indian",
        "promoters_foreign",
        "investors_indian",
        "investors_foreign",
        "others"
    ],
    "L22": [
        "single_premium_to_total",
        "linked_nb_to_total_nb",
        "retention_ratio",
        "eom_ratio",
        "commission_ratio",
        "bd_sales_to_nb_premium",
        "pat_to_total_income",
        "persistency_premium_13",
        "persistency_premium_25",
        "persistency_premium_37",
        "persistency_premium_49",
        "persistency_premium_61",
        "persistency_nop_13",
        "persistency_nop_25",
        "persistency_nop_37",
        "persistency_nop_49",
        "persistency_nop_61",
        "solvency_ratio",
        "avg_ticket_size"
    ],
    "L37": [
        "schemes_agency", "schemes_banca", "schemes_ca", "schemes_broking",
        "schemes_micro", "schemes_direct", "schemes_imf", "schemes_others", "schemes_total",
        "premium_agency", "premium_banca", "premium_ca", "premium_broking",
        "premium_micro", "premium_direct", "premium_imf", "premium_others", "premium_total",
        "lives_agency", "lives_banca", "lives_ca", "lives_broking",
        "lives_micro", "lives_direct", "lives_imf", "lives_others", "lives_total"
    ],
    "L38": [
        "nop_agency", "nop_banca", "nop_ca", "nop_broking", "nop_micro",
        "nop_direct_website", "nop_direct_others", "nop_imf", "nop_csc",
        "nop_web_aggregator", "nop_pos", "nop_others", "nop_total",
        "premium_agency", "premium_banca", "premium_ca", "premium_broking", "premium_micro",
        "premium_direct_website", "premium_direct_others", "premium_imf", "premium_csc",
        "premium_web_aggregator", "premium_pos", "premium_others", "premium_total"
    ],
    "L39_individual": [
        "maturity_on_or_before", "maturity_1m", "maturity_1_3m", "maturity_3_6m",
        "maturity_6m_1y", "maturity_1y_plus", "maturity_total_claims", "maturity_total_amount",
        "survival_on_or_before", "survival_1m", "survival_1_3m", "survival_3_6m",
        "survival_6m_1y", "survival_1y_plus", "survival_total_claims", "survival_total_amount",
        "annuity_on_or_before", "annuity_1m", "annuity_1_3m", "annuity_3_6m",
        "annuity_6m_1y", "annuity_1y_plus", "annuity_total_claims", "annuity_total_amount",
        "surrender_on_or_before", "surrender_1m", "surrender_1_3m", "surrender_3_6m",
        "surrender_6m_1y", "surrender_1y_plus", "surrender_total_claims", "surrender_total_amount",
        "other_on_or_before", "other_1m", "other_1_3m", "other_3_6m",
        "other_6m_1y", "other_1y_plus", "other_total_claims", "other_total_amount",
        "death_on_or_before", "death_1m", "death_1_3m", "death_3_6m",
        "death_6m_1y", "death_1y_plus", "death_total_claims"
    ],
    "L39_group": [
        "maturity_on_or_before", "maturity_1m", "maturity_1_3m", "maturity_3_6m",
        "maturity_6m_1y", "maturity_1y_plus", "maturity_total_claims", "maturity_total_amount",
        "survival_on_or_before", "survival_1m", "survival_1_3m", "survival_3_6m",
        "survival_6m_1y", "survival_1y_plus", "survival_total_claims", "survival_total_amount",
        "annuity_on_or_before", "annuity_1m", "annuity_1_3m", "annuity_3_6m",
        "annuity_6m_1y", "annuity_1y_plus", "annuity_total_claims", "annuity_total_amount",
        "surrender_on_or_before", "surrender_1m", "surrender_1_3m", "surrender_3_6m",
        "surrender_6m_1y", "surrender_1y_plus", "surrender_total_claims", "surrender_total_amount",
        "other_on_or_before", "other_1m", "other_1_3m", "other_3_6m",
        "other_6m_1y", "other_1y_plus", "other_total_claims", "other_total_amount",
        "death_on_or_before", "death_1m", "death_1_3m", "death_3_6m",
        "death_6m_1y", "death_1y_plus", "death_total_claims"
    ],
    "L41": [
        "total_policies",
        "total_claims",
        "policy_complaints_per_10000",
        "claim_complaints_per_10000"
    ],
    "L45": [
        "branch_opening",
        "branch_approved",
        "branch_opened",
        "branch_closed",
        "branch_total",
        "branch_rural",
        "branch_urban",
        "employee_onrole",
        "employee_offrole",
        "agent_counts",
        "bank",
        "ca",
        "broker",
        "web_agg",
        "imf",
        "micro",
        "pos",
        "others"
    ]
}
